version: '3.8'
services:
  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - DB_HOST=server
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - DB_NAME=shareit
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      #- spring.datasource.url=jdbc:h2:mem:${DB_NAME}


  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password